const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={passed:true,checks:[]};
function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.checked=false;this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};
const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');
code=code.replace(/\n  if \(document\.readyState === 'loading'\) \{/,`\nwindow.KFTest={AppState,startNewCareer,playerContractBaseSalary,playerContractUntilSeason,currentSquadFormationKey,playerIssueCount,kf021CleanupLegacyPlayerStatusFields,migrateWorldDataTruthToCurrent,applyLineupFormation};\n  if (document.readyState === 'loading') {`);
vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
T.startNewCareer();const w=T.AppState.world;
const players=(w.players.order||[]).map(id=>w.players.byId[id]).filter(Boolean);
const contracted=players.filter(p=>p.clubId&&!p.retired&&!p.loan || p.clubId&&!p.retired);
const legacyContractFields=['salary','contractUntilSeason','contractUntilDisplay'];
const legacyContractPlayers=players.filter(p=>legacyContractFields.some(k=>Object.prototype.hasOwnProperty.call(p,k)));
const clubPlayers=players.filter(p=>p.clubId&&!p.retired);
const invalidContracts=clubPlayers.filter(p=>!p.contract||p.contract.salaryBase==null||p.contract.validUntilSeason==null);
check('Current player contracts have one canonical contract object',invalidContracts.length===0,{clubPlayers:clubPlayers.length,invalid:invalidContracts.slice(0,5).map(p=>p.id)});
check('Legacy player salary/contract-until scalar fields are absent from current worlds',legacyContractPlayers.length===0,{count:legacyContractPlayers.length,sample:legacyContractPlayers.slice(0,5).map(p=>p.id)});
const salaryMismatch=clubPlayers.filter(p=>Math.abs(T.playerContractBaseSalary(p)-Number((p.contract||{}).salaryBase||0))>1e-9);
check('Salary helper reads exactly player.contract.salaryBase',salaryMismatch.length===0,{count:salaryMismatch.length});
const clubs=(w.clubs.order||[]).map(id=>w.clubs.byId[id]).filter(Boolean);
const legacyFormationClubs=clubs.filter(c=>Object.prototype.hasOwnProperty.call(c,'currentFormationKey'));
const missingFormationClubs=clubs.filter(c=>!w.squads[c.id]||!w.squads[c.id].lineupMaskState||!w.squads[c.id].lineupMaskState.formationKey);
check('Current formation exists in world.squads for every club',missingFormationClubs.length===0,{count:missingFormationClubs.length,sample:missingFormationClubs.slice(0,5).map(c=>c.id)});
check('Club objects no longer duplicate currentFormationKey',legacyFormationClubs.length===0,{count:legacyFormationClubs.length});
const formationClub=clubs[0],formationSquad=w.squads[formationClub.id],formationBefore=T.currentSquadFormationKey(w,formationClub),formationAlt=(windowObj.KFStaticData.formations||[]).map(f=>f.id).find(id=>id&&id!==formationBefore);
if(formationAlt)T.applyLineupFormation(formationClub,formationSquad,w,formationAlt);
check('Changing formation writes only the squad formation truth',!formationAlt||(T.currentSquadFormationKey(w,formationClub)===formationAlt&&!Object.prototype.hasOwnProperty.call(formationClub,'currentFormationKey')),{before:formationBefore,after:T.currentSquadFormationKey(w,formationClub),target:formationAlt});
const sample=clubPlayers[0];sample.injuryWeeksLeft=2;delete sample.injurySlotsLeft;
const beforeKeys=Object.prototype.hasOwnProperty.call(sample,'injuryWeeksLeft');const issueRead=T.playerIssueCount(sample,['injuryWeeksLeft','injured']);
check('Reading injury status does not migrate or mutate legacy fields',issueRead===0&&beforeKeys&&Object.prototype.hasOwnProperty.call(sample,'injuryWeeksLeft')&&!Object.prototype.hasOwnProperty.call(sample,'injurySlotsLeft'),{issueRead});
const migrated=T.kf021CleanupLegacyPlayerStatusFields(w);
check('Explicit injury migration converts legacy fields to injurySlotsLeft',migrated>=1&&sample.injurySlotsLeft===4&&!Object.prototype.hasOwnProperty.call(sample,'injuryWeeksLeft'),{migrated,slots:sample.injurySlotsLeft});
// Explicit legacy 0.22-style contract + formation migration.
const c=clubs[0],p0=w.players.byId[(w.squads[c.id].playerIds||[])[0]],oldFormation=c.preferredFormationKey;
p0.salary=1.234;p0.contractUntilSeason=9;p0.contract={role:'starter'};c.currentFormationKey=oldFormation;
T.AppState.worldRecord.schemaVersion='kf-world-record-0.25.1';T.AppState.worldRecord.gameVersion='0.25.6';
const migration=T.migrateWorldDataTruthToCurrent(w);
check('Explicit schema migration absorbs legacy contract scalars then deletes them',Math.abs(p0.contract.salaryBase-1.234)<1e-9&&p0.contract.validUntilSeason===9&&!Object.prototype.hasOwnProperty.call(p0,'salary')&&!Object.prototype.hasOwnProperty.call(p0,'contractUntilSeason'),{migration,contract:p0.contract});
check('Explicit schema migration absorbs legacy currentFormationKey then deletes it',T.currentSquadFormationKey(w,c)===oldFormation&&!Object.prototype.hasOwnProperty.call(c,'currentFormationKey'),{migration,formation:T.currentSquadFormationKey(w,c)});
check('World schema is current and JSON-serializable',w.meta.schemaVersion==='kf-core-0.27.2'&&(()=>{try{return JSON.parse(JSON.stringify(w)).meta.schemaVersion==='kf-core-0.27.2'}catch(e){return false}})(),{schemaVersion:w.meta.schemaVersion});
check('WorldRecord schema remains compatible while gameVersion tracks KF_0.29.1',T.AppState.worldRecord.schemaVersion==='kf-world-record-0.27.2'&&T.AppState.worldRecord.gameVersion==='0.29.1',{schemaVersion:T.AppState.worldRecord.schemaVersion,gameVersion:T.AppState.worldRecord.gameVersion});
check('Data-truth metadata no longer labels current-season matches as the historical truth',!Object.prototype.hasOwnProperty.call(w.meta.dataTruth||{},'historicalMatches')&&(w.meta.dataTruth||{}).currentSeasonMatches==='world.history.matches (compact current-season index)'&&(w.meta.dataTruth||{}).currentSeasonMatchDetails==='CurrentSeasonMatchRepository[worldId][season][matchId]' &&(w.meta.dataTruth||{}).historicalResults==='world.history.seasonResults',{dataTruth:w.meta.dataTruth});
check('BonusEvents is no longer a persistent truth and stays empty',Array.isArray(w.history.bonusEvents)&&w.history.bonusEvents.length===0&&(w.meta.dataTruth||{}).processedFinancialEvents==='CurrentSeasonFinanceRepository financeEvents[].eventKey (current season only)',{bonusEvents:(w.history.bonusEvents||[]).length,dataTruth:w.meta.dataTruth});
const out=path.join(root,'reports','current_data_truth_invariants_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
