const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');const read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={version:'0.25.1',passed:true,checks:[],metrics:{}};function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E(),'sim-progress-text':new E()};
const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const mathObj=Object.create(Math); const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance,Math:mathObj});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');
code=code.replace(/\n  function boot\(\)\{/,`\n  window.KFTest={AppState,startNewCareer,simulateLeagueFixture,kf0251BaseSimulateLeagueFixture,recordPlayedMatch,kf0251ArchiveSeasonMatches,kf0251EnsureNormalMinimumRosters,playerFieldAssignment,totalAnnualSalaryForClub,playerContractSalaryBreakdownForClub,ensureRuntimeDerivedIndex,RuntimeDerivedIndexByWorld,runtimeWorldKey,runtimeMatchStamp,kf021ProcessMatchContractBonuses,recentMatchesForClub};\n  function boot(){`);
vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
function seeded(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296;};}
function sig(m){return JSON.stringify({hg:m.homeGoals,ag:m.awayGoals,xg:m.matchStats&&m.matchStats.expectedGoals,events:m.events,playerStats:m.playerStats,homeLineup:m.homeLineup,awayLineup:m.awayLineup,usedTactics:m.usedTactics});}
T.startNewCareer();let w=T.AppState.world;
check('World schema is migrated to current KF_0.26.2 runtime',w.meta&&w.meta.schemaVersion==='kf-core-0.27.1',{schema:w.meta&&w.meta.schemaVersion});
// Aufstellung: waehle einen tatsaechlich auf dem Feld platzierten Spieler.
const club=w.clubs.byId[w.clubs.order[0]],squad=w.squads[club.id],fieldId=(squad.lineup||[])[0]||(squad.playerIds||[])[0];
let assignment=null,error=null;try{assignment=T.playerFieldAssignment(club,squad,fieldId);}catch(e){error=String(e);}check('Aufstellungszuordnung wirft keinen world-ReferenceError',!error&&assignment&&assignment.slotId,{error,assignment});
// Matchcache: gleicher Weltzustand + gleiche RNG-Folge => exakt gleiche Signatur.
vm.runInContext('Date.now=function(){return 1700000000000;};',context); const fixture=w.calendar.fixtures.find(f=>f.competition==='league');const wA=JSON.parse(JSON.stringify(w)),wB=JSON.parse(JSON.stringify(w));const fA=wA.calendar.fixtures.find(f=>f.id===fixture.id),fB=wB.calendar.fixtures.find(f=>f.id===fixture.id);
context.Math.random=seeded(2501);T.AppState.world=wA;const base=T.kf0251BaseSimulateLeagueFixture(wA,fA);context.Math.random=seeded(2501);T.AppState.world=wB;const cached=T.simulateLeagueFixture(wB,fB);check('Matchlokaler Cache veraendert die Matchsignatur nicht',sig(base)===sig(cached),{base:`${base.homeGoals}:${base.awayGoals}`,cached:`${cached.homeGoals}:${cached.awayGoals}`});
// Runtime-Matchindex wird inkrementell erweitert.
T.AppState.world=w;const idxBefore=T.ensureRuntimeDerivedIndex(w,'matches');const idxObj=idxBefore;const f=w.calendar.fixtures.find(x=>x.competition==='league'&&x.status!=='played');context.Math.random=seeded(99);const r=T.simulateLeagueFixture(w,f);T.recordPlayedMatch(w,f,r);const idxAfter=T.ensureRuntimeDerivedIndex(w,'matches');check('Matchindex bleibt beim Speichern dasselbe Runtime-Objekt',idxObj===idxAfter&&idxAfter.matchById[r.id]===r,{matchId:r.id});
// Bonus-Deduplizierung.
const st=(r.playerStats||[]).find(s=>s&&s.playerId);if(st){const p=w.players.byId[st.playerId];p.contract=p.contract||{};p.contract.bonuses=p.contract.bonuses||{};p.contract.bonuses.appearanceBonus=0.01;const before=(w.history.bonusEvents||[]).length;T.kf021ProcessMatchContractBonuses(w,r);const once=(w.history.bonusEvents||[]).length;T.kf021ProcessMatchContractBonuses(w,r);const twice=(w.history.bonusEvents||[]).length;check('BonusEvents werden bei Wiederholung nicht doppelt verbucht',once>=before&&twice===once,{before,once,twice});}
// Gehaltsdirektpfad ist fachlich identisch zum bisherigen Breakdowngrundgehalt.
let salaryDiff=0;for(const id of w.clubs.order){salaryDiff=Math.max(salaryDiff,Math.abs(Number(T.totalAnnualSalaryForClub(w,id)||0)-Number(T.playerContractSalaryBreakdownForClub(w,id,'current').baseSalary||0)));}check('Direkte Gehaltsbasis entspricht Vertragsprojektion',salaryDiff<0.0001,{maxDifference:salaryDiff});
// Saisonarchiv: Spielerstatistiken/Matchnote bleiben, Detailereignisse schrumpfen.
const sample=[];for(let i=0;i<12;i++){const fx=w.calendar.fixtures.find(x=>x.competition==='league'&&x.status!=='played');if(!fx)break;context.Math.random=seeded(500+i);const rr=T.simulateLeagueFixture(w,fx);T.recordPlayedMatch(w,fx,rr);sample.push(rr);}const statsBefore=JSON.stringify(sample.map(m=>m.playerStats));const bytesBefore=Buffer.byteLength(JSON.stringify(sample));const archived=T.kf0251ArchiveSeasonMatches(w,1);const bytesAfter=Buffer.byteLength(JSON.stringify(sample));const statsAfter=JSON.stringify(sample.map(m=>m.playerStats));check('Saisonarchiv behaelt Spielerstatistiken und Bewertungen',statsBefore===statsAfter&&sample.every(m=>m.historyArchived),{archived});check('Saisonarchiv reduziert Matchdaten',bytesAfter<bytesBefore,{bytesBefore,bytesAfter,reductionPct:+((1-bytesAfter/bytesBefore)*100).toFixed(1)});
// Recent-Matches-Index liefert die neuesten Spiele des Vereins.
const recent=T.recentMatchesForClub(w,r.homeClubId,5);check('Club-Matchindex liefert hoechstens die letzten fuenf Spiele',recent.length<=5&&recent.every(m=>m.homeClubId===r.homeClubId||m.awayClubId===r.homeClubId),{count:recent.length});
report.metrics={checks:report.checks.length,archiveReductionPct:+((1-bytesAfter/bytesBefore)*100).toFixed(1),maxSalaryDifference:salaryDiff};
const out=path.join(root,'reports','kf_0.25.1_fix_regression_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
