const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={passed:true,checks:[],metrics:{}};function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};
const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{values:{},setProperty(k,v){this.values[k]=v}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');code="(function(){let s=230023;Math.random=function(){s=(s*1664525+1013904223)>>>0;return s/4294967296;};})();\n"+code;code=code.replace(/\n  if \(document\.readyState === 'loading'\) \{/,`\n  window.KFTest={AppState,startNewCareer,buildFinanceSnapshot,renderFinanceOverviewTab,kf0214ProjectFutureRoster,kf0214EnsureClubSalaryBudget,kf0214SalaryBudgetFloor,kf0214IncomeCalibration,kf0214TargetPosition,kf0214ProjectedPlacementForCurrentSeason,kf0211LicenceSquadMarketValue,kf0211ApplyLicenceMetrics,kf0211Rules,financeCurrentCash,financeEventSum,financePlacementBonus,estimateCurrentSeasonCupBonus,playerContractSalaryBreakdownForClub,clubContractContextIndex,scheduleFutureMovement,kf021FutureFinanceAdjustments,kf0214BookFinalPlacementBonuses,recordLicenceDecisionForSeasonEnd,transferPhaseState,quickPlayerMatchStrength};\n  if (document.readyState === 'loading') {`);vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
T.startNewCareer();const w=T.AppState.world,season=Number(w.meta.seasonNumber||1);const q=(a,p)=>{a=[...a].sort((x,y)=>x-y);return a[Math.max(0,Math.min(a.length-1,Math.round((a.length-1)*p)))]};
check('App version is KF_0.29.1 while world schema stays KF_0.27.2',read('src/app.bundle.js').includes("KF_VERSION = '0.29.1';")&&read('src/app.bundle.js').includes("world.meta.schemaVersion='kf-core-0.27.2'")&&read('index.html').includes('KF_0.29.1')&&JSON.parse(read('package.json')).version==='0.29.1',{});
const cfg=(windowObj.KFStaticData||{}).financeBalance0214||{};
check('Country/league income calibration is central StaticData',cfg.incomeCalibrationByCountryLevel&&Object.keys(cfg.incomeCalibrationByCountryLevel).length===8,{countries:Object.keys(cfg.incomeCalibrationByCountryLevel||{})});

const baseRatios=[],overBudget=[],operating=[],groups={};
for(const id of w.clubs.order){const c=w.clubs.byId[id],squad=(w.squads[id]||{playerIds:[]}),base=(squad.playerIds||[]).reduce((sum,pid)=>{const p=w.players.byId[pid];return sum+Number((p&&p.contract&&p.contract.salaryBase)||0)},0),budget=Number(c.salaryBudget||0);baseRatios.push(budget>0?base/budget:999);if(base>budget+0.001)overBudget.push({id,name:c.name,league:c.leagueKey,base,budget});const sal=T.playerContractSalaryBreakdownForClub(w,id,'current').expectedSeasonCost,fin=w.clubFinances.byClub[id],current=T.financeCurrentCash(w,c),start=Number(fin.seasonStartCash||0),cup=T.estimateCurrentSeasonCupBonus(w,c).forecastRemaining,pos=T.kf0214TargetPosition(w,c,c.leagueKey,c.seasonTarget),placement=T.financePlacementBonus(c,pos),op=(current-start)-sal+cup+placement;operating.push(op);const k=c.countryName+'|L'+c.leagueLevel;(groups[k]||(groups[k]=[])).push(op);}
check('No generated start squad exceeds its base salary budget',overBudget.length===0,{overBudget:overBudget.slice(0,10),maxBaseBudgetRatio:Math.max(...baseRatios)});
check('Generated squads retain at least about eight percent board salary reserve',Math.max(...baseRatios)<=0.927,{maxBaseBudgetRatio:Math.max(...baseRatios),median:q(baseRatios,.5)});
const opMedian=q(operating,.5),within2=operating.filter(x=>Math.abs(x)<=2).length/operating.length*100,groupStats=Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,{median:q(v,.5),within2:v.filter(x=>Math.abs(x)<=2).length/v.length*100}])),maxGroupMedian=Math.max(...Object.values(groupStats).map(x=>Math.abs(x.median)));
check('Neutral club baseline plans around zero operating result',Math.abs(opMedian)<=0.50,{median:opMedian,p25:q(operating,.25),p75:q(operating,.75)});
check('Most clubs start within a credible two-million corridor around zero',within2>=80,{within2,negativePct:operating.filter(x=>x<0).length/operating.length*100,min:Math.min(...operating),max:Math.max(...operating)});
check('Every country/league median remains close to zero while differences survive',maxGroupMedian<=1.75,{maxGroupMedian,groups:groupStats});

const clubRisks=w.clubs.order.map(id=>({id,r:T.clubContractContextIndex(w,w.clubs.byId[id]).relegationRisk})).sort((a,b)=>a.r-b.r),cut=Math.max(1,Math.floor(clubRisks.length*0.20)),lowIds=new Set(clubRisks.slice(0,cut).map(x=>x.id)),highIds=new Set(clubRisks.slice(-cut).map(x=>x.id));
function clauseShares(set){let end=0,cutMode=0,total=0;for(const pid of w.players.order){const p=w.players.byId[pid];if(!p||!set.has(p.clubId)||!p.contract)continue;const cl=p.contract.clauses||{};total++;if(cl.relegationClauseMode==='contract_end')end++;if(cl.relegationClauseMode==='salary_change'&&Number(cl.relegationSalaryDecreasePercent||0)>0)cutMode++;}return{endShare:total?end/total:0,cutShare:total?cutMode/total:0,total};}
const lowShare=clauseShares(lowIds),highShare=clauseShares(highIds);
check('Surprise-relegation clubs use more contract-end clauses',lowShare.endShare>highShare.endShare,{lowRisk:lowShare,highRisk:highShare});
check('Relegation-threatened clubs use wage cuts more often',highShare.cutShare>lowShare.cutShare,{lowRisk:lowShare,highRisk:highShare});

const clubId=w.clubs.order.find(id=>Number(w.clubs.byId[id].leagueLevel)===2),club=w.clubs.byId[clubId],squad=w.squads[clubId],playerId=(squad.playerIds||[]).find(id=>{const p=w.players.byId[id];return p&&!p.loan&&p.contract&&Number(p.contract.validUntilSeason||0)>season;});const p=w.players.byId[playerId];
const originals=(squad.playerIds||[]).map(id=>{const x=w.players.byId[id];return{id,contract:JSON.stringify(x.contract||{}),market:x.marketValue};});
function normalizeClubClauses(){for(const id of squad.playerIds||[]){const x=w.players.byId[id];if(!x||!x.contract)continue;x.contract.clauses=x.contract.clauses||{};x.contract.clauses.relegationClauseMode='none';x.contract.clauses.relegationSalaryDecreasePercent=0;x.contract.clauses.releaseClauseType='none';x.contract.clauses.fixedReleaseFee=0;delete x.contract.clauses.freeRelegation;delete x.contract.triggeredSeasonEndSalaryChange;delete x.contract.triggeredSeasonEndTermination;}}
function restoreClub(){for(const o of originals){const x=w.players.byId[o.id];x.contract=JSON.parse(o.contract);x.marketValue=o.market;}}
normalizeClubClauses();const baseRoster=T.kf0214ProjectFutureRoster(w,club,'stay');
p.contract.validUntilSeason=season;const expiring=T.kf0214ProjectFutureRoster(w,club,'stay');check('Regularly expiring contract leaves future squad and licence asset',baseRoster.ownedPlayerIds.includes(playerId)&&!expiring.ownedPlayerIds.includes(playerId),{before:baseRoster.ownedCount,after:expiring.ownedCount});restoreClub();normalizeClubClauses();
p.contract.clauses.relegationClauseMode='contract_end';p.contract.clauses.relegationContractEnd=true;const stayEnd=T.kf0214ProjectFutureRoster(w,club,'stay'),downEnd=T.kf0214ProjectFutureRoster(w,club,'relegation');check('Relegation contract-end removes player only in relegation scenario',stayEnd.ownedPlayerIds.includes(playerId)&&!downEnd.ownedPlayerIds.includes(playerId),{stay:stayEnd.ownedCount,relegation:downEnd.ownedCount});restoreClub();normalizeClubClauses();
p.contract.clauses.relegationClauseMode='salary_change';p.contract.clauses.relegationSalaryDecreasePercent=40;const stayCut=T.kf0214ProjectFutureRoster(w,club,'stay'),downCut=T.kf0214ProjectFutureRoster(w,club,'relegation');check('Relegation wage cut keeps player but reduces scenario payroll',stayCut.ownedPlayerIds.includes(playerId)&&downCut.ownedPlayerIds.includes(playerId)&&downCut.salaryCost<stayCut.salaryCost,{staySalary:stayCut.salaryCost,relegationSalary:downCut.salaryCost});restoreClub();normalizeClubClauses();
p.marketValue=12;p.contract.clauses.releaseClauseType='none';let mv12=T.kf0214ProjectFutureRoster(w,club,'stay').marketValue;p.contract.clauses.releaseClauseType='fixed';p.contract.clauses.fixedReleaseFee=5;let mv5=T.kf0214ProjectFutureRoster(w,club,'stay').marketValue;check('Fixed release fee caps exploitable squad value',Math.abs((mv12-mv5)-7)<0.01,{withoutClause:mv12,withClause:mv5});restoreClub();normalizeClubClauses();

const saleWorld=JSON.parse(JSON.stringify(w)),saleClub=saleWorld.clubs.byId[clubId],saleP=saleWorld.players.byId[playerId],otherId=saleWorld.clubs.order.find(id=>id!==clubId),other=saleWorld.clubs.byId[otherId];saleP.marketValue=12;saleP.contract.clauses=saleP.contract.clauses||{};saleP.contract.clauses.releaseClauseType='fixed';saleP.contract.clauses.fixedReleaseFee=5;saleP.contract.clauses.relegationClauseMode='salary_change';saleP.contract.clauses.relegationSalaryDecreasePercent=30;T.scheduleFutureMovement(saleWorld,{type:'permanent',playerId:playerId,fromClubId:clubId,toClubId:other.id,fee:7,executionSeason:season+1,executionSlotKey:'w1-middle',contractOffer:null});const saleRoster=T.kf0214ProjectFutureRoster(saleWorld,saleClub,'relegation'),saleAdj=T.kf021FutureFinanceAdjustments(saleWorld,saleClub,'relegation');check('Binding seven-million sale beats later five-million clause',!saleRoster.ownedPlayerIds.includes(playerId)&&Math.abs(Number(saleAdj.nextNet||0)-7)<0.01,{owned:saleRoster.ownedPlayerIds.includes(playerId),nextTransferNet:saleAdj.nextNet});

const loanWorld=JSON.parse(JSON.stringify(w)),parent=loanWorld.clubs.byId[clubId],loanOtherId=loanWorld.clubs.order.find(id=>id!==clubId),loanOther=loanWorld.clubs.byId[loanOtherId],loanP=loanWorld.players.byId[playerId];loanP.loan={parentClubId:clubId,loanClubId:loanOtherId,endSeason:season+1,wageSharePercent:50};loanP.clubId=loanOtherId;loanWorld.squads[clubId].playerIds=loanWorld.squads[clubId].playerIds.filter(id=>id!==playerId);if(!loanWorld.squads[loanOtherId].playerIds.includes(playerId))loanWorld.squads[loanOtherId].playerIds.push(playerId);loanWorld.transferMarket=loanWorld.transferMarket||{};loanWorld.transferMarket.loanedOutByClub=loanWorld.transferMarket.loanedOutByClub||{};loanWorld.transferMarket.loanedOutByClub[clubId]=loanWorld.transferMarket.loanedOutByClub[clubId]||[];if(!loanWorld.transferMarket.loanedOutByClub[clubId].includes(playerId))loanWorld.transferMarket.loanedOutByClub[clubId].push(playerId);const parentRoster=T.kf0214ProjectFutureRoster(loanWorld,parent,'stay'),loanRoster=T.kf0214ProjectFutureRoster(loanWorld,loanOther,'stay');check('Own loaned-out player remains asset but is not active while loan continues',parentRoster.ownedPlayerIds.includes(playerId)&&!parentRoster.activePlayerIds.includes(playerId),{});check('Loaned-in player is active but never counted as owned asset',loanRoster.activePlayerIds.includes(playerId)&&!loanRoster.ownedPlayerIds.includes(playerId),{});

restoreClub();const asset=T.kf0211LicenceSquadMarketValue(w,clubId,'stay');function metric(pct){return T.kf0211ApplyLicenceMetrics(w,club,{scenario:'stay',nextResult:-asset.value*pct/100,futureRoster:T.kf0214ProjectFutureRoster(w,club,'stay')});}check('Licence thresholds remain exactly 5/15 percent',metric(5).licenceStatus==='Lizenz ohne Auflagen'&&metric(5.01).licenceStatus==='Lizenz mit Sanierungsauflagen'&&metric(15).licenceStatus==='Lizenz mit Sanierungsauflagen'&&metric(15.01).licenceStatus==='Lizenz verweigert',{});

const htmlStart=Date.now(),html=T.renderFinanceOverviewTab(w,club),renderMs=Date.now()-htmlStart;check('Future scenarios visibly explain squad size, strength and exploitable value',html.includes('Kader ')&&html.includes('St')&&html.includes('verwertbarer Kader'),{renderMs});check('Finance overview remains responsive after scenario projection',renderMs<500,{renderMs});

const finalWorld=JSON.parse(JSON.stringify(w)),finalClub=finalWorld.clubs.byId[clubId],finalOrder=finalWorld.clubs.order.slice();finalWorld.clubs.order=[clubId];const row={clubId:clubId,position:7},standings={};standings[finalClub.leagueKey]=[row];const beforeLevels={[clubId]:finalClub.leagueLevel},beforeKeys={[clubId]:finalClub.leagueKey};const beforePlacement=T.financeEventSum(finalWorld,clubId,season,ev=>ev.type==='placementBonus');T.recordLicenceDecisionForSeasonEnd(finalWorld,standings,beforeLevels,beforeKeys);const afterPlacement=T.financeEventSum(finalWorld,clubId,season,ev=>ev.type==='placementBonus');check('Final placement bonus is booked in old season before licence decision',afterPlacement>beforePlacement&&Math.abs(afterPlacement-T.financePlacementBonus(finalClub,7))<0.01,{beforePlacement,afterPlacement,expected:T.financePlacementBonus(finalClub,7)});finalWorld.clubs.order=finalOrder;

check('Current runtime source is the authoritative app bundle',fs.existsSync(path.join(root,'src','app.bundle.js'))&&!fs.existsSync(path.join(root,'src','app.bundle.generated.js')),{});
report.metrics={version:'0.27.0',checks:report.checks.length,clubs:w.clubs.order.length,operatingMedian:opMedian,withinTwoMillionPercent:within2,maxCountryLeagueMedianDeviation:maxGroupMedian,maxBaseBudgetRatio:Math.max(...baseRatios),renderMs};const out=path.join(root,'reports','current_finance_balance_licence_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
