const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');const report={passed:true,checks:[]};function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance,Map,WeakMap});for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});let code=read('src/app.bundle.js');code=code.replace(/\n  if \(document\.readyState === 'loading'\) \{/ , `\nwindow.KFTest={createEmptyWorld,createUserProfile,createWorldRecord,createTrainerForWorld,assignTrainerClub,isHumanControlledClub,activeMemberships,WorldRepository};\n  if (document.readyState === 'loading') {`);vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
const a=T.createWorldRecord({gameState:T.createEmptyWorld({seasonNumber:1}),createdByUserId:'u1'}),b=T.createWorldRecord({gameState:T.createEmptyWorld({seasonNumber:1}),createdByUserId:'u2'});
check('Separate worlds receive stable independent identities',a.id&&b.id&&a.id!==b.id,{a:a.id,b:b.id});a.gameState.players.byId.test={id:'test'};check('Football state is independent between WorldRecords',!b.gameState.players.byId.test&&a.gameState.players!==b.gameState.players&&a.memberships!==b.memberships,{});
for(const [r,prefix] of [[a,'a'],[b,'b']]){r.gameState.clubs.byId[prefix+'1']={id:prefix+'1'};r.gameState.clubs.order=[prefix+'1'];r.gameState.squads[prefix+'1']={playerIds:[]};const p=T.createUserProfile({id:'user-'+prefix});const t=T.createTrainerForWorld(p,r,{displayName:'Trainer '+prefix});T.assignTrainerClub(r,t.trainer.id,prefix+'1');}
check('Human control stays world-specific',T.isHumanControlledClub(a.gameState,'a1')&&!T.isHumanControlledClub(b.gameState,'a1')&&T.isHumanControlledClub(b.gameState,'b1'),{});
check('WorldRecord is JSON-serializable as server/save payload',(()=>{try{const x=JSON.parse(JSON.stringify(a));return x.id===a.id&&x.gameState.meta.id===a.id;}catch(e){return false;}})(),{});
const src=read('src/app.bundle.js');check('No single-human or singleplayer domain field remains in current gameState creation',!src.includes('.humanClubId')&&!src.includes('humanClubId:')&&!/mode:\s*['\"]singleplayer['\"]/.test(src)&&!src.includes('sourceSessionId: options.sessionId'),{});
const out=path.join(root,'reports','current_multiworld_readiness_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
