const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};
const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
let seed=270002;const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance,Math:math,Map,WeakMap,Set});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');code=code.replace(/\n  if \(document\.readyState === 'loading'\) \{/,`\n  window.KFTest={AppState,startNewCareer,simulateLeagueFixture,recordPlayedMatch,CurrentSeasonMatchRepository};\n  if (document.readyState === 'loading') {`);vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
T.startNewCareer();const w=T.AppState.world,TARGET=180,leagueKey=w.clubs.byId[w.clubs.order[0]].leagueKey;
const fixtures=(w.calendar.fixtures||[]).filter(f=>Number(f.season||1)===1&&f.status!=='played'&&f.competition==='league'&&f.leagueKey===leagueKey&&f.homeClubId&&f.awayClubId).slice(0,TARGET);
const t0=Date.now();for(const f of fixtures)T.recordPlayedMatch(w,f,T.simulateLeagueFixture(w,f));const simMs=Date.now()-t0;
const rows=w.history.matches||[];const field={};for(const m of rows){for(const [k,v] of Object.entries(m||{})){field[k]=(field[k]||0)+Buffer.byteLength(JSON.stringify(v))+Buffer.byteLength(JSON.stringify(k))+1;}}
const compactBytes=Buffer.byteLength(JSON.stringify(rows)),storeBytes=T.CurrentSeasonMatchRepository.serializedBytes(w,1);
function proposedStat(stat){if(!stat||!stat.playerId)return null;const active=Number(stat.appearances||0)>0||Number(stat.minutesPlayed||0)>0||Number(stat.goals||0)>0||Number(stat.assists||0)>0||Number(stat.yellow||0)>0||Number(stat.yellowRed||0)>0||Number(stat.red||0)>0||Number(stat.saves||0)>0||typeof stat.rating==='number';if(!active)return null;const out={playerId:stat.playerId};if(stat.clubId)out.clubId=stat.clubId;if(stat.side)out.side=stat.side;if(stat.starter)out.starter=true;if(Number(stat.appearances||0))out.appearances=Number(stat.appearances);if(Number(stat.minutesPlayed||0))out.minutesPlayed=Number(stat.minutesPlayed);for(const k of ['goals','assists','yellow','yellowRed','red','saves'])if(Number(stat[k]||0))out[k]=Number(stat[k]);if(typeof stat.rating==='number')out.rating=stat.rating;if(stat.matchPosition)out.matchPosition=stat.matchPosition;return out;}
const proposedRows=rows.map(m=>{const o=Object.assign({},m);o.playerStats=(m.playerStats||[]).map(proposedStat).filter(Boolean);return o;});const proposedBytes=Buffer.byteLength(JSON.stringify(proposedRows));
const out={version:'0.27.0',matches:rows.length,simMs,compactBytes,proposedBytes,proposedReductionPct:+((1-proposedBytes/compactBytes)*100).toFixed(1),storeBytes,ratio:compactBytes/storeBytes,proposedRatio:proposedBytes/storeBytes,fieldBytes:Object.entries(field).sort((a,b)=>b[1]-a[1]).map(([key,bytes])=>({key,bytes,pct:+(bytes/compactBytes*100).toFixed(1)}))};
fs.writeFileSync(path.join(root,'reports','kf_0.27.0_compact_index_profile_test.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
