const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={passed:true,checks:[],metrics:{}};function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance});for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');code=code.replace(/\n  if \(document\.readyState === 'loading'\) \{/,`\nwindow.KFTest={AppState,startNewCareer,setSuspensionStatus,playerSuspensionApplies,playerUnavailableForCompetition,decrementActiveStatusesForSlot,resetPlayersForNewSeason,assistantPlayerAvailable}; if(typeof playerSuspensionEntries==='function') window.KFTest.playerSuspensionEntries=playerSuspensionEntries; if(typeof playerSuspensionCount==='function') window.KFTest.playerSuspensionCount=playerSuspensionCount;\n  if (document.readyState === 'loading') {`);vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
T.startNewCareer();const w=T.AppState.world,club=w.clubs.byId[w.clubs.order[0]],other=w.clubs.byId[w.clubs.order[1]],player=w.players.byId[w.squads[club.id].playerIds[0]];
T.setSuspensionStatus(player,'red','league','league_red',2);T.setSuspensionStatus(player,'red','national-cup','cup_red',1);
const entries=T.playerSuspensionEntries?T.playerSuspensionEntries(player):[];
check('League and cup suspensions coexist independently',entries.length===2&&entries.some(s=>s.competition==='league'&&s.matchesLeft===2)&&entries.some(s=>s.competition==='national-cup'&&s.matchesLeft===1),{entries,legacyCompetition:player.suspensionCompetition,legacyLeft:player.suspensionMatchesLeft});
check('Competition availability only blocks the matching suspension',T.playerUnavailableForCompetition(player,'league')===true&&T.playerUnavailableForCompetition(player,'national-cup')===true&&T.playerUnavailableForCompetition(player,'fiebercup')===false,{});
check('Lineup assistant can use player in league when only cup-suspended',(()=>{const p=w.players.byId[w.squads[club.id].playerIds[1]];T.setSuspensionStatus(p,'red','national-cup','cup_only',1);return T.assistantPlayerAvailable(p,'league')===true&&T.assistantPlayerAvailable(p,'national-cup')===false;})(),{});
T.decrementActiveStatusesForSlot(w,[{homeClubId:club.id,awayClubId:other.id,competition:'league'}]);
const afterLeague=T.playerSuspensionEntries?T.playerSuspensionEntries(player):[];
check('Playing league serves only league suspension',afterLeague.some(s=>s.competition==='league'&&s.matchesLeft===1)&&afterLeague.some(s=>s.competition==='national-cup'&&s.matchesLeft===1),{entries:afterLeague});
T.decrementActiveStatusesForSlot(w,[{homeClubId:club.id,awayClubId:other.id,competition:'national-cup'}]);
const afterCup=T.playerSuspensionEntries?T.playerSuspensionEntries(player):[];
check('Cup suspension clears without touching remaining league suspension',afterCup.length===1&&afterCup[0].competition==='league'&&afterCup[0].matchesLeft===1,{entries:afterCup});
T.setSuspensionStatus(player,'yellow','fiebercup','yellow_end',1);T.resetPlayersForNewSeason(w);const afterSeason=T.playerSuspensionEntries?T.playerSuspensionEntries(player):[];
check('Yellow suspensions expire at season rollover while red suspensions persist',afterSeason.some(s=>s.reason==='red'&&s.competition==='league')&&!afterSeason.some(s=>s.reason==='yellow'),{entries:afterSeason});
check('Legacy single-suspension scalar fields are not the canonical storage',Array.isArray(player.suspensions)&&!Object.prototype.hasOwnProperty.call(player,'suspensionMatchesLeft')&&!Object.prototype.hasOwnProperty.call(player,'suspensionCompetition'),{hasArray:Array.isArray(player.suspensions),legacyLeft:player.suspensionMatchesLeft,legacyCompetition:player.suspensionCompetition});
report.metrics={version:'0.27.0-current',checks:report.checks.length};const out=path.join(root,'reports','current_suspension_model_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
