const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={version:'0.27.0',passed:true,checks:[],metrics:{}};
function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}closest(){return null}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()};
const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
let seed=262001;const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()},localStorage:{getItem(){return null},setItem(){}}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance,Math:math,Map,WeakMap,Set});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js');
code=code.replace(/\n\n  if \(document\.readyState === 'loading'\) \{/,`\n  window.KFTest={AppState,startNewCareer,calculatePlayerCurrentOverallAdvanced,calculateGroupRatingsAdvanced,weightedOverallFromRatings,kf0262SampleDisplayedStrengths,kf0262AverageStrengthForPlayer,runPlayerFinancialValuation,playerMarketValueHistoryForPlayer,retirePlayersForSeasonEnd,kf0262RetiredPlayerById,migrateWorldDataTruthToCurrent,renderPlayerStrengthChart,openPlayerProfile,renderPlayerProfileModal};\n\n  if (document.readyState === 'loading') {`);
vm.runInContext(code,context,{filename:'src/app.bundle.js'});if(document.cb)document.cb();const T=windowObj.KFTest;
check('Runtime meldet KF_0.29.2',code.includes("var KF_VERSION = '0.29.2';")&&read('index.html').includes('KF_0.29.2')&&JSON.parse(read('package.json')).version==='0.29.2');
T.startNewCareer();const w=T.AppState.world;
check('Neuwelt nutzt neue Schemata und Ruheständler-Container',w.meta.schemaVersion==='kf-core-0.27.2'&&w.history.retiredPlayers&&w.history.retiredPlayers.byId&&Array.isArray(w.history.retiredPlayers.order),{schema:w.meta.schemaVersion});
const cacheExact=w.players.order.slice(0,40).every((id,i)=>{const x=w.players.byId[id];x.form=1+(i%10);x.fitness=1+((i*3)%10);x.morale=1+((i*7)%10);const ref=T.weightedOverallFromRatings(x.mainPosition,T.calculateGroupRatingsAdvanced(x,{includeStaticModifiers:true,includeConditions:true,includeDynamicModifiers:true}));return ref===T.calculatePlayerCurrentOverallAdvanced(x);});
check('Performance-Cache liefert exakt dieselbe angezeigte Stärke wie die vollständige zentrale Berechnung',cacheExact,{});
const originalOrder=w.players.order.slice(),playerId=originalOrder[0],p=w.players.byId[playerId];
// Keep the functional test small: the world remains complete, but valuation/sampling iterates only the selected test player.
w.players.order=[playerId];
p.form=4;p.fitness=5;p.morale=5;const s1=Number(T.calculatePlayerCurrentOverallAdvanced(p));const r1=T.kf0262SampleDisplayedStrengths(w,'kf0262-sample-a');
p.form=10;p.fitness=10;p.morale=10;const s2=Number(T.calculatePlayerCurrentOverallAdvanced(p));const r2=T.kf0262SampleDisplayedStrengths(w,'kf0262-sample-b');
p.form=1;const duplicate=T.kf0262SampleDisplayedStrengths(w,'kf0262-sample-b');const avg=T.kf0262AverageStrengthForPlayer(w,playerId),expected=Math.round(((s1+s2)/2)*100)/100;
check('Stärke-Akkumulator mittelt angezeigte Stärke und zählt Slots nur einmal',r1.sampled===1&&r2.sampled===1&&duplicate.duplicate===true&&Math.abs(avg-expected)<.001,{s1,s2,avg,expected,duplicate});
const serializedAccumulator=JSON.parse(JSON.stringify(w.meta.playerStrengthAccumulator));w.meta.playerStrengthAccumulator=serializedAccumulator;p.form=8;p.fitness=8;p.morale=8;const s3=Number(T.calculatePlayerCurrentOverallAdvanced(p));T.kf0262SampleDisplayedStrengths(w,'kf0262-sample-c');const avgReload=T.kf0262AverageStrengthForPlayer(w,playerId),expectedReload=Math.round(((s1+s2+s3)/3)*1000)/1000;
check('Save/Reload erhält laufenden Halbserien-Akkumulator',Math.abs(avgReload-expectedReload)<.001,{s3,avgReload,expectedReload});
const staleOverall=Number(p.overall||0);p.form=3;p.fitness=4;p.morale=4;const currentLow=Number(T.calculatePlayerCurrentOverallAdvanced(p));T.runPlayerFinancialValuation(w,'initial',{history:false});const marketLow=Number(p.marketValue||0);p.form=10;p.fitness=10;p.morale=10;const currentHigh=Number(T.calculatePlayerCurrentOverallAdvanced(p));T.runPlayerFinancialValuation(w,'initial',{history:false});const marketHigh=Number(p.marketValue||0);
check('Marktwert reagiert trotz unverändertem player.overall auf sichtbare Form/Fitness/Moral-Stärke',staleOverall===Number(p.overall||0)&&currentHigh>currentLow&&marketHigh>marketLow,{staleOverall,currentLow,currentHigh,marketLow,marketHigh});
// Clean accumulator for one checkpoint.
w.meta.marketValuationCheckpoints={};w.meta.playerStrengthAccumulator={season:Number(w.meta.seasonNumber||1),period:'firstHalf',lastSampleSlot:null,validFromPeriodStart:true,byPlayerId:{}};p.form=5;p.fitness=6;p.morale=6;const hs1=Number(T.calculatePlayerCurrentOverallAdvanced(p));T.kf0262SampleDisplayedStrengths(w,'hist-a');p.form=9;p.fitness=9;p.morale=9;const hs2=Number(T.calculatePlayerCurrentOverallAdvanced(p));T.kf0262SampleDisplayedStrengths(w,'hist-b');const val=T.runPlayerFinancialValuation(w,'midseason',{history:true}),rows=T.playerMarketValueHistoryForPlayer(w,playerId),havg=Math.round(((hs1+hs2)/2)*100)/100;
check('Marktwert-Historie speichert am Stichtag denselben Zeitachsenpunkt mit averageStrength',val.strengthEntries===1&&rows.length===1&&rows[0].phase==='midseason'&&Math.abs(Number(rows[0].averageStrength)-havg)<.001,{row:rows[0],havg,strengthEntries:val.strengthEntries});
check('Stärkeverlauf kann aus derselben Historie gerendert werden',T.renderPlayerStrengthChart(p).includes('Stärkeverlauf')&&T.renderPlayerStrengthChart(p).includes(String(rows[0].averageStrength)),{averageStrength:rows[0].averageStrength});
// Retirement compaction on one selected player.
const retireId=originalOrder.find(id=>{const x=w.players.byId[id];return x&&x.clubId;});const retireP=w.players.byId[retireId],clubId=retireP.clubId;w.players.order=[retireId];retireP.plannedRetirementAge=retireP.age;retireP.retirementExtensionLimit=1;retireP.retirementExtensionsUsed=1;const beforeKeys=Object.keys(retireP).length,ret=T.retirePlayersForSeasonEnd(w,Number(w.meta.seasonNumber||1)),arch=T.kf0262RetiredPlayerById(w,retireId);const squadStill=Object.values(w.squads||{}).some(sq=>(sq.playerIds||[]).includes(retireId)||(sq.lineup||[]).includes(retireId)||(sq.bench||[]).includes(retireId)||(sq.reserve||[]).includes(retireId));
check('Ruheständler verschwindet vollständig aus aktivem Spielerbestand und Kadern',ret.retired.includes(retireId)&&!w.players.byId[retireId]&&!w.players.order.includes(retireId)&&!squadStill,{clubId,retired:ret.retired.includes(retireId)});
const forbidden=['contract','fitness','form','morale','ballControl','dribbling','injurySlotsLeft','salaryExpectation'];
check('Ruheständlerprofil ist kompakt und enthält keine aktiven Simulationsdaten',!!arch&&arch.lastClubId===clubId&&arch.retiredSeason===Number(w.meta.seasonNumber||1)&&forbidden.every(k=>!Object.prototype.hasOwnProperty.call(arch,k))&&Object.keys(arch).length<beforeKeys,{archiveKeys:Object.keys(arch),beforeKeys});
T.openPlayerProfile(retireId);const retiredHtml=T.renderPlayerProfileModal();
check('Historisches Spielerprofil bleibt erreichbar und bietet nur historische Bereiche',retiredHtml.includes('Karriere beendet')&&retiredHtml.includes('Statistik')&&retiredHtml.includes('Karriereverlauf')&&!retiredHtml.includes('Fähigkeiten')&&!retiredHtml.includes('Vertrag verlängern'),{htmlLength:retiredHtml.length});
// Simulate a legacy full retired player without cloning the full world.
const legacyId=originalOrder.find(id=>id!==retireId&&w.players.byId[id]),legacyP=w.players.byId[legacyId];w.players.order=[];legacyP.retired=true;legacyP.retiredSeason=1;legacyP.retirementReason='age';w.meta.schemaVersion='kf-core-0.26.1';delete w.history.retiredPlayers;delete w.meta.playerStrengthAccumulator;const mig=T.migrateWorldDataTruthToCurrent(w);
check('0.26.1-Migration überführt alte vollständige Ruheständler ohne erfundene Stärkehistorie',mig.retiredPlayersMigrated===1&&!w.players.byId[legacyId]&&!!w.history.retiredPlayers.byId[legacyId]&&!((w.history.playerMarketValues||{})[legacyId]||[]).some(row=>row.averageStrength!=null),{migration:mig.retiredPlayersMigrated,schema:w.meta.schemaVersion});
report.metrics={sampleAverage:avgReload,marketLow,marketHigh,historyAverage:rows[0].averageStrength,archiveKeys:Object.keys(arch).length};
const out=path.join(root,'reports','kf_0.26.2_player_lifecycle_strength_test.json');fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,reportFile:out},null,2));process.exit(report.passed?0:1);
