const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'); const read=r=>fs.readFileSync(path.join(root,r),'utf8');
const report={passed:true,checks:[],metrics:{}}; function check(name,ok,details={}){report.checks.push({name,ok:!!ok,details});if(!ok)report.passed=false;}
class E{constructor(){this.innerHTML='';this.style={};this.dataset={};this.value='';this.classList={add(){},remove(){},contains(){return false}}}addEventListener(){}removeEventListener(){}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}querySelector(){return null}querySelectorAll(){return[]}getBoundingClientRect(){return{width:1760,height:990}}}
const els={'app-root':new E(),'modal-root':new E(),'app-shell':new E()}; const document={readyState:'loading',documentElement:{clientWidth:1760,clientHeight:990,style:{setProperty(){}}},body:new E(),getElementById:id=>els[id]||null,addEventListener(t,cb){if(t==='DOMContentLoaded')this.cb=cb},removeEventListener(){},createElement(){return new E()},querySelector(){return null},querySelectorAll(){return[]}};
const windowObj={innerWidth:1760,innerHeight:990,addEventListener(){},removeEventListener(){},requestAnimationFrame:cb=>cb(),cancelAnimationFrame(){},console,setTimeout,clearTimeout,document,Element:E,navigator:{userAgent:'node-test'},performance:{now:()=>Date.now()}};
const context=vm.createContext({window:windowObj,document,console,setTimeout,clearTimeout,Element:E,navigator:windowObj.navigator,performance:windowObj.performance});
for(const f of ['src/static-data.js','src/db1-db2-data.js'])vm.runInContext(read(f),context,{filename:f});
let code=read('src/app.bundle.js'); code=code.replace(/\n  function boot\(\)\{/,`\n  window.KFTest={AppState,startNewCareer,ensureKF021CoreContainers,kf021MigrateLegacyInjuryState,kf021PayInterClubBonus,assignTrainerClub};\n  function boot(){`);
vm.runInContext(code,context,{filename:'src/app.bundle.js'}); if(document.cb)document.cb(); const T=windowObj.KFTest; T.startNewCareer(); const w=T.AppState.world;
check('World schema carries explicit KF_0.26.2 schema version',w.meta.schemaVersion==='kf-core-0.27.1',{schemaVersion:w.meta.schemaVersion});
check('World schema documents central current/historical truths',w.meta.dataTruth&&w.meta.dataTruth.currentPlayers==='world.players.byId'&&w.meta.dataTruth.currentSquads==='world.squads'&&w.meta.dataTruth.currentSeasonMatches==='world.history.matches'&&w.meta.dataTruth.historicalResults==='world.history.seasonResults'&&w.meta.dataTruth.historicalPlayerSeasons==='world.history.playerSeasons',w.meta.dataTruth||{});
check('Core top-level containers exist from career creation',!!(w.transferMarket&&w.transferMarket.futureMoves&&w.transferMarket.activeClauses&&w.transferMarket.loanedOutByClub&&w.negotiations&&w.mailbox&&w.seasonLifecycle&&w.scouting&&w.squadPlanning),{});
const player=w.players.byId[w.players.order[0]]; player.injuryWeeksLeft=3; delete player.injurySlotsLeft; const slots=T.kf021MigrateLegacyInjuryState(player);
check('Legacy injury duration migrates once to slot truth',slots===6&&player.injurySlotsLeft===6,{slots,injurySlotsLeft:player.injurySlotsLeft});
check('Legacy injury fields are removed instead of mirrored',!['injuryMatchesLeft','injuryWeeksLeft','injuryDaysLeft','injuryGamesLeft','injuryCount','injured'].some(k=>Object.prototype.hasOwnProperty.call(player,k)),Object.keys(player).filter(k=>k.startsWith('injury')));
const clubs=w.clubs.order.slice(0,2); T.AppState.session.activeClubId=clubs[0]; T.assignTrainerClub(T.AppState.worldRecord,T.AppState.session.activeTrainerId,clubs[0]); const before=w.mailbox.order.length; const paid=T.kf021PayInterClubBonus(w,clubs[0],clubs[1],player,.5,'Testklausel','cleanup-mail-test'); const after=w.mailbox.order.length;
check('Relevant transfer-clause payment creates a Mailcenter notification for human club',paid&&after===before+1,{before,after,mail:w.mailbox.byId[w.mailbox.order[0]]});
const out=path.join(root,'reports','current_data_mail_integrity_test.json'); fs.mkdirSync(path.dirname(out),{recursive:true}); fs.writeFileSync(out,JSON.stringify(report,null,2)); console.log(JSON.stringify({...report,reportFile:out},null,2)); process.exit(report.passed?0:1);
